config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  root 'sessions#new'
  resources :usrs
  
  namespace :admin do
    resources :usrs
  end
  resources :labelings
  resources :labels
  
  # root 'tasks#index'
  resources :tasks
  
  resources :sessions
  # devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usr.rb
class Usr < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_many :labels, dependent: :destroy
    validates :name, presence: true, length: {maximum: 40}
   validates :email, presence: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
   validates :email, uniqueness: true
   before_validation { email.downcase! }
   has_secure_password
  validates :password, presence: true
  def self.admins
    @users = Usr.all
  @admins=0
    @users.each do |user|
      if user.admin?
        @admins += 1
      end
    end
    return @admins
  end



end

app/controllers/admin/usrs_controller.rb
class Admin::UsrsController < ApplicationController
  before_action :require_admin
  before_action :set_usr, only: [:show, :edit, :update]
  # before_action :only_see_own_page, only: [:show]
  # before_action :only_create_user_when_none_signed_in,  only:[:new, :create]
  
  def require_admin
    unless current_user.try(:admin?)
      redirect_to root_path, notice: "are you admin?please login"
    end
  end 



  def index
    @usrs = Usr.all
    @tasks=Task.all
  end
 
  def show
    @user_tasks=Task.order(:created_at).includes(:usr)
  end

  # GET /usrs/new
  def new
    @usr = Usr.new
  end

  # GET /usrs/1/edit
  def edit
  end

  # POST /usrs
  # POST /usrs.json
  def create
    @usr = Usr.new(usr_params)

    respond_to do |format|
      if @usr.save
        session[:usr_id] = @usr.id
        if @usr.admin?
        format.html { redirect_to admin_usrs_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @usr }
         else 
          format.html { redirect_to tasks_url, notice: 'Usr was successfully created.' }
    
           format.json { render :show, status: :created, location: @usr }
        end
      else
        format.html { render :new }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usrs/1
  # PATCH/PUT /usrs/1.json
  def update
    respond_to do |format|
      if @usr.update(usr_params)
        format.html { redirect_to @usr, notice: 'Usr was successfully updated.' }
        format.json { render :show, status: :ok, location: @usr }
      else
        format.html { render :edit }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usrs/1
  # DELETE /usrs/1.json
  def destroy
    @usr = Usr.find(params[:id])
    if @usr.id == current_user.id
      redirect_to admin_usrs_url, notice: "You can not delete signed in user"
      @admins = Usr.admins
    elsif @admins == 1
      redirect_to admin_usrs_url, notice: "At least one admin must remain!"
    else
      @usr.destroy
      redirect_to admin_usrs_url, notice: 'User was successfully destroyed.'
    end
  end



  private
  def only_see_own_page
    @user = Usr.find(params[:id])
    if current_user != @user
      redirect_to usrs_path, notice: "Sorry, but you are only allowed to view your own profile page."
    end
  end
 
 def only_create_user_when_none_signed_in
    if current_user
      redirect_to usrs_path,  notice: "you can't create user when signed in"
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_usr
      @usr = Usr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usr_params
      params.require(:usr).permit(:name, :email, :password, :confirm_password, :admin)
    end
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  before_action :set_usr, only: [:show, :edit, :update]
  # before_action :only_see_own_page, only: [:show,:destroy, :edit]
  # before_action :only_create_user_when_none_signed_in , only:[:new, :create]
  # GET /usrs
  # GET /usrs.json
  def index
    @usrs = Usr.all
  end

  # GET /usrs/1
  # GET /usrs/1.json
  def show
    @user_tasks=Task.order(:created_at).includes(:usr)
  end

  # GET /usrs/new
  def new
    @usr = Usr.new
  end

  # GET /usrs/1/edit
  def edit
  end

  # POST /usrs
  # POST /usrs.json
  def create
    @usr = Usr.new(usr_params)

    respond_to do |format|
      if @usr.save
         session[:usr_id] = @usr.id
         if @usr.admin?
          format.html { redirect_to admin_usrs_url, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @usr }
           else 
             format.html { redirect_to tasks_url, notice: 'Usr was successfully created.' }
      
             format.json { render :show, status: :created, location: @usr }
          end
        format.html { render :new }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usrs/1
  # PATCH/PUT /usrs/1.json
  def update
    respond_to do |format|
      if @usr.update(usr_params)
        format.html { redirect_to @usr, notice: 'Usr was successfully updated.' }
        format.json { render :show, status: :ok, location: @usr }
      else
        format.html { render :edit }
        format.json { render json: @usr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usrs/1
  # DELETE /usrs/1.json
  def destroy
    @usr = Usr.find(params[:id])
    if @usr.id == current_user.id
      redirect_to admin_usrs_url, notice: "You can not delete signed in user"
      @admins = Usr.admins
    elsif @admins == 1
      redirect_to admin_usrs_url, notice: "At least one admin must remain!"
    else
      @usr.destroy
      redirect_to admin_usrs_url, notice: 'User was successfully destroyed.'
    end
  end

  

  private
  def only_see_own_page
    @user = Usr.find(params[:id])
    if current_user != @user
      redirect_to usrs_path, notice: "Sorry, but you are only allowed to view your own profile page."
    end
  end
 
 def only_create_user_when_none_signed_in
    if current_user
      redirect_to usrs_path,  notice: "you can't create user when signed in"
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_usr
      @usr = Usr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usr_params
      params.require(:usr).permit(:name, :email, :password, :confirm_password, :admin)
    end
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/admin/usrs/_form.html.erb
<%= form_with(model: usr, local: true) do |form| %>
  <% if usr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usr.errors.count, "error") %> prohibited this usr from being saved:</h2>

      <ul>
      <% usr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="card">
  <div class="card-body">   
  <h1>New  User</h1>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :confirm_password %>
    <%= form.password_field :confirm_password %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.radio_button :admin, 'true' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create User',class:"btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', usrs_path, class:"btn btn-dark" %>
  
  </div>
</div>



  

app/views/admin/usrs/edit.html.erb
<h1>Editing Usr</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Show', @usr %> |
<%= link_to 'Back', usrs_path %>

app/views/admin/usrs/index.html.erb
<h1 style="color:blue;">Welcome to user management page</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th>No of tasks</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @usrs.each do |usr| %>
      <tr>
        <td><%= usr.name %></td>
        <td><%= usr.email %></td>
        <td><%= usr.admin %></td>
        <td> <%= Task.where(usr_id: usr.id).count %></td>
        <td><%= link_to 'Show', usr, class:"btn btn-warning"%></td>
        <td><%= link_to 'Edit', edit_usr_path(usr), class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', usr, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_usr_path, class:"btn btn-success" %>


<h1 style="color:blue;margin-top:2rem">List of Tasks Created</h1>
<%= form_tag(tasks_path, method: :get) do %>
 Enter Title or Status
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', class:"btn btn-success"%>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Created date</th>
      <th>Expire date</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.usr.name %></td>
        <td><%= task.created_at %></td>
        <td><%= task.expired_date %></td>
        <td><%= task.priority %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task, class:"btn btn-warning"%></td>
        <td><%= link_to 'Edit', edit_task_path(task),class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Task', new_task_path, class:"btn btn-success"  %>
<br>
<br><br>

app/views/admin/usrs/new.html.erb
<%= render 'form', usr: @usr %>

app/views/admin/usrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usr.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usr.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @usr.password_digest %>
</p>


<p>
  <strong>Admin:</strong>
  <%= @usr.admin %>
</p>

<p> <h2> Tasks Submitted By This User</h2>
<% @user_tasks.each do |task| %>
<% if @usr.id == task.usr_id %>
<ul>
<li class = "user-tasks">
 Name:<%= task.title %> <br/>Content:<%= task.content %>
</li>
</ul>
 <% end %>
<% end %>
</p>


<%= link_to 'Edit', edit_usr_path(@usr) %> |
<%= link_to 'Back', usrs_path %>