config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  root 'sessions#new'
  resources :usrs
  
  namespace :admin do
    resources :usrs
  end
  resources :labelings
  resources :labels
  
  # root 'tasks#index'
  resources :tasks
  
  resources :sessions
  # devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryLeaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  
<nav class="navbar navbar-expand" style="background-color:#64b2cd">
  <ul class="navbar-nav" style="color:blue">
    <li class="nav-item active">
      <a class="nav-link" href="#">Task Management</a>
    </li>
   
    <li class="nav-item" >
    <a class="nav-link" <%= link_to 'Home', tasks_path %></a>
    </li>
    <li class="nav-item" >
    <a class="nav-link" <%= link_to 'New Task', new_task_path %></a>
    </li>
    <li class="nav-item" >
    <a class="nav-link" <%= link_to 'New Label', new_label_url %></a>
    </li>
    <li class="nav-item" >
    <a class="nav-link" <%= link_to 'Users', usrs_path %></a>
    </li>
    <% if logged_in? %>
    <% if current_user.admin? %>

    <li class="nav-item" >
    <a class="nav-link" <%= link_to 'Go to admin page', admin_usrs_url %></a>
    </li>
    <%end %>
    <%end %>
    <% if logged_in? %>
    <li class="nav-item">
    <a class="nav-link" <%= link_to "Logout", session_path(current_user.id), method: :delete%> </a>
  
    </li>
    <% end %>
    
  </ul>
</nav>
<% if logged_in? %>
    <p class="wel"> Logged in as , <%=current_user.name %> </p><br>
   
    <% end %>




  
  <body>
  <h1 id="notice"><%= notice %></h1>
    <%= yield %>






    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>